name: doc

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  doc-deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --group doc --dev
      - run: uv run mkdocs gh-deploy --force